# Generated by Django 5.2 on 2025-04-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
